// Generated by CoffeeScript 1.6.2
(function() {
  (function() {
    return $(function() {
      var command_pressed;

      $('body').append('<div class="readmelater-snapshot"></div>');
      command_pressed = false;
      $(window).keydown(function(e) {
        var temp;

        if (String.fromCharCode(e.keyCode).toLowerCase() === 's' && (e.ctrlKey || command_pressed)) {
          e.preventDefault();
          if (temp = localStorage.getItem('readmelater') || '{}') {
            console.log(document.URL);
            console.log(temp);
            temp = JSON.parse(temp);
            localStorage.setItem('readmelater', (temp[document.URL] = document.title, JSON.stringify(temp)));
            return setTimeout();
          }
        } else if (e.keyCode === 91) {
          return command_pressed = true;
        }
      });
      $(window).keyup(function(e) {
        if (e.keyCode === 91) {
          return command_pressed = false;
        }
      });
      return window.onblur = function() {
        return command_pressed = false;
      };
    });
  })();

}).call(this);
